### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [stastnypremysl/Chatovatko#4]
Hello! @stastnypremysl 

I am a graphic designer and i wanted to contribute for chatovatko. I designed a logo for it. 

Please tell me what you think and what you want. I will wait for feedback. Have a nice day!

![1](https://user-images.githubusercontent.com/36298335/43959129-74427c62-9cb6-11e8-91ea-63cbae854305.jpg)

**Comment by stastnypremysl** [comment]
Hello! @reallinfo 

Thank you for you contribution. 
The shape of logo is very nice. But I don't like the color and the text. 
I would rather use black as dominating color. And the blue just for some not thick line/lines.

Could you, please, send me original files in a vector image format?
Thank you.

Could you, please, send the original files in svg or some other vector format?
Thank you very much.

**Comment by reallinfo** [comment]
I sent a svg format via pr. if you have a font you want i can create another variation. Do you want to try another type of font. I don't really understand what colors you want.  if the file I send dont contains the colors you want, I can send a new one.

**Comment by stastnypremysl** [comment]
Thank you. I really appritiate your help. If you don't mind, I will think about graphics problems when I have done backend.

I am probably going to use your logo, but I don't know the colors of app interface yet, so maybe I will need to change color and font later. But it is meaningless to speak about it now.

**Comment by stastnypremysl** [comment]
I have used your logo in unfinished beta version UWP and Android application.
If you have any ideas, how to improve project, I would be very grateful for them.
